name: App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        swift: ['5.3']
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -scheme DistributedChatApp
      working-directory: DistributedChatApp

